[book]
authors = ["Tyson Thomas"]
language = "en"
src = "src"
title = "Programming 1 - Javascript"

[output.html]
site-url='/programming1js-book/'
additional-js = ["js/highlightjs-line-numbers.js"]
mathjax-support = true

[output.html.playground]
line-numbers = true


